run:
	javac -cp "./lib/algs4.jar" ./src/$(JAVA_FILE).java
	java -cp "./lib/algs4.jar;./bin/" $(JAVA_FILE) < ./src/tinyUf.txt 

perco:
	javac -cp "./lib/algs4.jar" ./src/PercolationStats.java
	java -cp "./lib/algs4.jar;./bin/" PercolationStats 200 100